server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: catalog-ms
  data:
    mongodb:
      uri: mongodb://catalog_db:password@localhost:27017/catalog_db?authSource=admin
      database: catalog_db
